# Multiple Linear Regression

(lasso and ridge algorithm is also used below)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\programming\\python\\jupyter\\ML\\files\\house_price_prediction.csv")
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3,2.0,325.00,2900.0,3,11206.896550,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x=df.drop("price",axis=1)             #axis=1 means the whole column;  axis=0 means the whole row

In [4]:
x

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3,2.0,1672.0,3,8971.291866,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,3,3.0,1750.0,3,8514.285714,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3,2.0,1750.0,3,8571.428571,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2,2.0,1250.0,2,3200.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2,2.0,1200.0,2,6916.666667,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3,2.0,2900.0,3,11206.896550,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7116,3,1.0,1780.0,3,4765.730337,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2,1.0,880.0,2,5454.545455,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7118,2,1.0,1000.0,2,5500.000000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7119,2,1.0,1400.0,3,5571.428571,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
x.shape

(7120, 107)

In [6]:
y=df["price"]

In [7]:
y

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...
7115    325.00
7116     84.83
7117     48.00
7118     55.00
7119     78.00
Name: price, Length: 7120, dtype: float64

In [8]:
y.shape

(7120,)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=51)

In [11]:
x_train.shape

(5696, 107)

In [12]:
y_train.shape

(5696,)

In [13]:
x_test.shape

(1424, 107)

In [14]:
y_test.shape

(1424,)

In [15]:
x_train

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
7112,5,2.0,2500.0,6,7400.000000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2169,2,0.0,995.0,2,4623.115578,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
47,2,2.0,1180.0,2,7500.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
446,2,1.0,1450.0,3,5862.068966,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2650,2,1.0,1197.0,2,6432.748538,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672,2,1.0,1246.0,2,5457.463884,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1733,2,1.0,1010.0,2,5742.574257,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1760,2,2.0,1080.0,2,4629.629630,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
485,2,2.0,982.0,2,2500.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2105,2,1.0,1000.0,2,2888.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
x_test

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
2435,3,1.584376,1700.0,3,4705.882353,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3113,2,2.000000,1016.0,2,3937.007874,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
426,4,2.000000,1950.0,3,6153.846154,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1124,2,1.000000,1350.0,2,5851.851852,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1161,2,1.000000,850.0,2,5294.117647,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,2,1.000000,1090.0,2,2600.000000,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6855,3,1.000000,1585.0,3,5299.684543,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4381,1,2.000000,665.0,1,4812.030075,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3862,2,1.000000,1167.0,2,5398.457584,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,2,0.000000,1566.0,2,11494.252870,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
y_train

7112    185.00
2169     46.00
47       88.50
446      85.00
2650     77.00
         ...
6672     68.00
1733     58.00
1760     50.00
485      24.55
2105     28.88
Name: price, Length: 5696, dtype: float64

In [18]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [19]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [20]:
sc=StandardScaler()

In [21]:
sc.fit(x_train)

StandardScaler()

In [22]:
x_train=sc.transform(x_train)    #using standard scaler algo, 
x_test=sc.transform(x_test)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
lr=LinearRegression()

In [25]:
lr.fit(x_train,y_train)

LinearRegression()

In [26]:
lr.coef_                 #used to show the value of m (slope)

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468907e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029427e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968546e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886277e-01,  8.03443207e-01,  2.99182164e+00,  3.86430422e-03,
        1.05037260e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -8.23059458e-01, -9.07215235e-01,  1.22059216e+00,
        2.11418894e+00, -5.38187400e-01, -1.32164338e+00, -8.28349339e-01,
        1.28167980e+00, -1.92911295e-01,  6.65824486e-02,  3.65563139e-02,
       -1.85069853e+00,  1.49068024e+00, -9.57964753e-01, -9.36110163e-01,
       -7.45634897e-01,  7.22643164e-02, -6.79260144e-01, -1.70853833e-01,
       -1.72288643e+00, -1.15833746e+00,  5.78931788e-01,  1.37836966e+00,
       -1.14424496e+00,  3.96188294e-01, -6.08013157e-01, -2.20959218e+00,
        3.45270810e-01,  1.01747448e-03,  1.06563895e-01,  3.04728530e+00,
        2.09496392e+00, -8.13481923e-01, -4.18437282e-01,  2.30993396e+00,
        3.31858799e-02,  8.07865914e-02,  5.37064987e-02,  1.55347699e+00,
        8.13889657e-01, -1.14636462e+00,  3.41805788e-01, -8.28022037e-01,
        1.68897360e+00,  2.97657524e-01,  9.59437517e-01,  4.57297702e-01,
       -2.22729515e-01, -1.48290835e+00, -6.26342867e-01,  5.86538254e-01,
       -1.78547310e+00,  2.19020231e-01, -3.45032599e-01])

In [27]:
lr.intercept_              #used to find the value of constatnt term C

95.0802729985955

In [28]:
x_test[0,:]              #[row,column]     here 0 represents thr index of row

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06226825,
       -0.05935999, -0.05935999, -0.05935999, -0.05630391, -0.05935999,
       -0.05785186, -0.05935999, -0.05935999, -0.06083125, -0.06083125,
       -0.05471275, -0.06083125, -0.06226825, -0.05935999, -0.05935999,
       -0.06226825, -0.06226825, -0.05785186, -0.06504853, -0.06226825,
       -0.06083125, -0.05935999, -0.05307449, -0.05630391, -0.06226825,
       -0.05471275, -0.05935999, -0.05471275, -0.05471275, -0.05138463,
       -0.05307449, -0.05307449, -0.05471275, -0.05471275, -0.05630391,
       -0.05630391, -0.05138463])

In [29]:
lr.predict([x_test[0,:]])

array([76.90661876])

In [30]:
lr.predict(x_test)

array([ 76.90661876,  15.25005377, 113.68281651, ...,  21.30296863,
        71.43462963, 230.04146251])

In [31]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [32]:
lr.score(x_test,y_test)

0.790383709251345

# Lasso and Ridge algorithm

In [33]:
from sklearn.linear_model import Ridge,Lasso

In [34]:
rd=Ridge()

In [35]:
rd.fit(x_train,y_train)

Ridge()

In [36]:
rd.score(x_test,y_test)

0.7905686374168057

In [37]:
ld=Lasso()

In [38]:
ld.fit(x_train,y_train)

Lasso()

In [39]:
ld.score(x_test,y_test)

0.8036373003386006

In [40]:
rd1=Ridge(alpha=2)
rd1.fit(x_train,y_train)
rd1.score(x_test,y_test)

0.7907530260229596

In [41]:
ld1=Lasso(alpha=2)
ld1.fit(x_train,y_train)
ld1.score(x_test,y_test)

0.8160181533586186

In [42]:
y_pred=lr.predict(x_test)
y_pred

array([ 76.90661876,  15.25005377, 113.68281651, ...,  21.30296863,
        71.43462963, 230.04146251])

In [43]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [44]:
import numpy as np
from sklearn.metrics import mean_squared_error   #used to find the error of actual value and predicted value

In [45]:
mse=mean_squared_error(y_test,y_pred)    #mean square error

In [46]:
mse

4211.806906162502

In [47]:
rmse=np.sqrt(mse)           #root mean square error (shows the avg error)
rmse

64.89843531366917