In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:\\programming\\python\\jupyter\\ML\\files\\house_price_prediction.csv")
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3,2.0,325.00,2900.0,3,11206.896550,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
x=df.drop("price",axis=1)             #axis=1 means the whole column;  axis=0 means the whole row

In [5]:
x

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3,2.0,1672.0,3,8971.291866,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,3,3.0,1750.0,3,8514.285714,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3,2.0,1750.0,3,8571.428571,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2,2.0,1250.0,2,3200.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2,2.0,1200.0,2,6916.666667,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3,2.0,2900.0,3,11206.896550,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7116,3,1.0,1780.0,3,4765.730337,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2,1.0,880.0,2,5454.545455,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7118,2,1.0,1000.0,2,5500.000000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7119,2,1.0,1400.0,3,5571.428571,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
x.shape

(7120, 107)

In [7]:
y=df["price"]

In [8]:
y

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...
7115    325.00
7116     84.83
7117     48.00
7118     55.00
7119     78.00
Name: price, Length: 7120, dtype: float64

In [9]:
y.shape

(7120,)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=51)

In [12]:
x_train.shape

(5696, 107)

In [13]:
y_train.shape

(5696,)

In [14]:
x_test.shape

(1424, 107)

In [15]:
y_test.shape

(1424,)

In [16]:
x_train

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
7112,5,2.0,2500.0,6,7400.000000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2169,2,0.0,995.0,2,4623.115578,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
47,2,2.0,1180.0,2,7500.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
446,2,1.0,1450.0,3,5862.068966,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2650,2,1.0,1197.0,2,6432.748538,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672,2,1.0,1246.0,2,5457.463884,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1733,2,1.0,1010.0,2,5742.574257,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1760,2,2.0,1080.0,2,4629.629630,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
485,2,2.0,982.0,2,2500.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2105,2,1.0,1000.0,2,2888.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
x_test

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
2435,3,1.584376,1700.0,3,4705.882353,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3113,2,2.000000,1016.0,2,3937.007874,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
426,4,2.000000,1950.0,3,6153.846154,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1124,2,1.000000,1350.0,2,5851.851852,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1161,2,1.000000,850.0,2,5294.117647,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,2,1.000000,1090.0,2,2600.000000,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6855,3,1.000000,1585.0,3,5299.684543,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4381,1,2.000000,665.0,1,4812.030075,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3862,2,1.000000,1167.0,2,5398.457584,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,2,0.000000,1566.0,2,11494.252870,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
y_train

7112    185.00
2169     46.00
47       88.50
446      85.00
2650     77.00
         ...
6672     68.00
1733     58.00
1760     50.00
485      24.55
2105     28.88
Name: price, Length: 5696, dtype: float64

In [19]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

K Nearest Neighbors regression

In [22]:
from sklearn.neighbors import KNeighborsRegressor

In [23]:
knr=KNeighborsRegressor(n_neighbors=5)

In [24]:
knr.fit(x_test,y_test)

KNeighborsRegressor()

In [25]:
knr.score(x_test,y_test)

0.8492670258662469

In [26]:
knr.predict([x_test.iloc[-1,:]])

C:\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

array([168.2])

In [27]:
y_test.iloc[-1]

180.0

In [28]:
x_test.iloc[-1,:]

bath                               2.00000
balcony                            0.00000
total_sqft_int                  1566.00000
bhk                                2.00000
price_per_sqft                 11494.25287
                                  ...
location_Hosur Road                0.00000
location_Horamavu Banaswadi        0.00000
location_Domlur                    0.00000
location_Mahadevpura               0.00000
location_Tumkur Road               0.00000
Name: 43, Length: 107, dtype: float64

In [29]:
predict=knr.predict(x_test)

In [30]:
predict

array([ 79.966,  41.02 , 120.4  , ...,  32.75 ,  64.6  , 168.2  ])

In [32]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [33]:
import numpy as np
from sklearn.metrics import mean_squared_error   #used to find the error of actual value and predicted value

In [34]:
mse=mean_squared_error(y_test,predict)    #mean square error

In [35]:
mse

3028.6681401313194

In [36]:
rmse=np.sqrt(mse)           #root mean square error (shows the avg error)
rmse

55.03333662546111